# Generated by Django 6.0.2 on 2026-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=10)),
                ('Is_active', models.BooleanField(default=True)),
                ('Is_staff', models.BooleanField(default=False)),
                ('Is_Admin', models.BooleanField(default=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
