from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("AdminDashboard/",views.AdminDashboard,name = "AdminDashboard"),
    path("BuyerDashboard/",views.BuyerDashboard,name = "BuyerDashboard"),
    path("SellerDashboard/",views.SellerDashboard,name = "SellerDashboard"),
    path("privacypolicy/",views.privacypolicy,name = "privacypolicy"),
    path("termsofservice/",views.termsofservice,name = "termsofservice"),   
    path("contactus/",views.ContactUs,name = "ContactUs"),
    path("helpcenter/",views.HelpCenter,name = "HelpCenter"),
    path("security/",views.Security,name = "Security"),
    path("community/",views.Community,name = "Community"),
    path("support/",views.Support,name = "Support"),
    path("aboutus/",views.AboutUs,name = "AboutUs"),
    path("careers/",views.Careers,name = "Careers"),
    path("howitworks/",views.HowItWorks,name = "HowItWorks"),
    path("create_auction/",views.create_auction,name = "create_auction"),
    path("auction_list/",views.auction_list,name = "auction_list"),
    path("auction/<int:pk>/",views.auction_detail,name = "auction_detail"),
    path("seller_profile/",views.seller_profile,name = "seller_profile"),
    path("buyer_profile/",views.buyer_profile,name = "buyer_profile"),
    path("admin_profile/",views.admin_profile,name = "admin_profile"),
    path("manage_categories/",views.manage_categories,name = "manage_categories"),
    path('manage_auctions/',views.manage_auctions,name='manage_auctions'),
    path('manage_items/',views.manage_items,name='manage_items'),
    path('manage_bids/',views.manage_bids,name='manage_bids'),
    path('manage_payments/',views.manage_payments,name='manage_payments'),
    path('manage_disputes/',views.manage_disputes,name='manage_disputes'),
    path('manage_notifications/', views.manage_notifications,name='manage_notifications'),
    path('manage_reviews/',views.manage_reviews,name='manage_reviews'),
    path('manage_watchlist/',views.manage_watchlist,name='manage_watchlist'),
    path('manage_activity_log/',views.manage_activity_log,name='manage_activity_log'),
    path('seller_manage_bids/',views.seller_manage_bids,name='seller_manage_bids'),
    path('dashboard_redirect/',views.dashboard_redirect,name='dashboard_redirect'),
]