# Generated by Django 6.0.2 on 2026-03-16 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_category_image_item_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_bid_placed', models.BooleanField(default=True)),
                ('notif_outbid', models.BooleanField(default=True)),
                ('notif_auction_won', models.BooleanField(default=True)),
                ('notif_payment', models.BooleanField(default=True)),
                ('notif_dispute', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('show_bids', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
