# Generated by Django 6.0.2 on 2026-03-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
