# Generated by Django 6.0.2 on 2026-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_dispute_is_seen_payment_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
