# Generated by Django 6.0.2 on 2026-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_review_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
